import * as THREE from 'three';

import { SeededRng } from '../../src/sim/Playbook.ts';
import {
  FIXED_DT,
  createDiscState,
  simulate,
  throwDisc,
} from '../../src/sim/DiscPhysics.ts';
import { THROW_SPECS, THROW_TYPES, throwSpeed, throwSpinRate } from '../../src/sim/aero/Throws.ts';
import {
  AERO,
  DISC,
  dragCoeff,
  liftCoeff,
  pitchCoeff,
  reverseBlend,
  stallBlend,
  zeroLiftAlpha,
} from '../../src/sim/aero/Coeffs.ts';

/* ---------------------------------------------------------------- coeffs */

/**
 * The coefficient curves, sampled across the full alpha domain.
 *
 * The sweep is dense and uniform so nothing is cherry-picked, but the named
 * angles matter more than the sweep does: they sit exactly on the boundaries
 * where the curves are piecewise — the stall blend's two ends, the zero-lift
 * angle, the far end of the reversal — and a port that gets the smoothstep
 * clamping subtly wrong passes a coarse sweep and fails precisely there.
 */
export function coeffGoldens() {
  const z = zeroLiftAlpha(AERO);

  const named: Record<string, number> = {
    zero: 0,
    zeroLift: z,
    // Both sides of each piecewise boundary, since a `<=` written as `<`
    // (or a clamp applied one step late) only shows up on one side.
    stallStart: AERO.aStall,
    stallStartBelow: AERO.aStall - 1e-9,
    stallEnd: AERO.aStall + AERO.aStallWidth,
    stallEndAbove: AERO.aStall + AERO.aStallWidth + 1e-9,
    stallMid: AERO.aStall + AERO.aStallWidth / 2,
    revStart: z - 1e-9,
    revEnd: z - AERO.revWidth,
    revEndBelow: z - AERO.revWidth - 1e-9,
    revMid: z - AERO.revWidth / 2,
    trim: -AERO.CM0 / AERO.CMa, // near the zero-moment angle
    quarterPi: Math.PI / 4,
    halfPi: Math.PI / 2,
    pi: Math.PI,
    negHalfPi: -Math.PI / 2,
    negPi: -Math.PI,
  };

  // 361 samples, one per half-degree over the full domain.
  const sweep: number[] = [];
  for (let i = 0; i <= 360; i++) sweep.push(-Math.PI + (i / 360) * 2 * Math.PI);

  const sample = (alpha: number) => ({
    alpha,
    stallBlend: stallBlend(alpha, AERO),
    reverseBlend: reverseBlend(alpha, AERO),
    lift: liftCoeff(alpha, AERO),
    drag: dragCoeff(alpha, AERO),
    pitch: pitchCoeff(alpha, AERO),
  });

  return {
    note:
      'Generated by tools/gen-goldens.ts from src/sim/aero/Coeffs.ts. ' +
      'stallBlend and reverseBlend are pure arithmetic and must port bit-exact; ' +
      'lift, drag and pitch call sin/tanh and get a tolerance.',
    disc: DISC,
    aero: AERO,
    zeroLiftAlpha: z,
    named: Object.fromEntries(
      Object.entries(named).map(([k, alpha]) => [k, sample(alpha)]),
    ),
    sweep: sweep.map(sample),
  };
}
