import * as THREE from 'three';
import { EventBus, QUALITY_PRESETS, Rng, type Ctx } from '../../src/core/Ctx.ts';
import { GameSystem } from '../../src/sim/Game.ts';

/**
 * `Game.ts`'s `lineUpForPull()`, captured directly. Issue #56: `Engine.stagePoint`'s
 * opening formation used to be a different, generic shape (`(slot/span - 0.5) * width *
 * 0.6`, `z = -dir * goalLine * 0.95`) rather than a port of `lineUpForPull`
 * (`x = -SIDELINE + 3.5 + (i/6) * (2*SIDELINE - 7)`, `z = -dir*GOAL_LINE + dir*0.5`) —
 * found while building `pull.json` for #48, which sidesteps the question entirely by
 * engineering the puller's body directly rather than trusting the formation. This
 * fixture pins the position `lineUpForPull` actually gives every player on the roster,
 * at the zero-tick instant it runs, so a real match's opening shape can be checked
 * instead of only the pull-throw formula that fires once a puller is wherever he ends
 * up.
 *
 * `GameSystem.init(ctx)` runs `buildRoster`, `startGame` (which enters `PRE_PULL` and
 * dispatches `onPhaseChange` → `lineUpForPull()`) in that order and returns with nobody
 * moved a tick — so the roster's `loco.pos`/`facing` are read straight off `init`,
 * exactly the same zero-tick instant `pull.json` captures `doPull` at, and for the same
 * reason: nothing has drawn from `ctx.rand` yet to disagree about.
 */

function makeCtx(seed: number): Ctx {
  return {
    renderer: null as unknown as THREE.WebGLRenderer,
    scene: null as unknown as THREE.Scene,
    camera: null as unknown as THREE.PerspectiveCamera,
    composer: null,
    time: 0, dt: 0, rawDt: 0, timeScale: 1, frame: 0,
    width: 1920, height: 1080, dpr: 1,
    quality: { ...QUALITY_PRESETS.high },
    events: new EventBus(),
    rand: new Rng(seed),
    sys: Object.create(null),
    debug: false,
    capture: false,
  };
}

/** Same seed set as `pull.json` — spread across puller/handedness, nothing tuned. */
const SEEDS = [11, 22, 33, 44, 55, 66, 77, 88];

function runOneLineup(seed: number) {
  const ctx = makeCtx(seed);
  const game = new GameSystem() as unknown as {
    init(ctx: Ctx): void;
    roster: {
      id: number; team: number;
      loco: { pos: { x: number; y: number; z: number }; facing: number };
    }[];
    gs: { pullingTeam: number; attackDir: [number, number]; phase: string };
  };

  game.init(ctx);

  return {
    seed,
    pullingTeam: game.gs.pullingTeam,
    phase: game.gs.phase,
    attackDir: [game.gs.attackDir[0], game.gs.attackDir[1]],
    roster: game.roster
      .slice()
      .sort((a, b) => a.id - b.id)
      .map((r) => ({
        id: r.id,
        team: r.team,
        pos: { x: r.loco.pos.x, y: r.loco.pos.y, z: r.loco.pos.z },
        facing: r.loco.facing,
      })),
  };
}

export function lineupGoldens() {
  const cases = SEEDS.map(runOneLineup);
  return {
    note:
      "Generated by tools/gen-goldens.ts from src/sim/Game.ts's lineUpForPull(), captured " +
      "at the same zero-tick instant pull.json captures doPull() at — see " +
      "tools/goldens/lineup.ts (issue #56). Each case is one seed's full roster " +
      "position/facing straight out of GameSystem.init(ctx), before any update() tick. " +
      "The Swift side (LineupTests.swift) builds Engine(format: .sevens, seed:) with a " +
      "matching startingPullTeam and reads positions straight out of init, which runs " +
      "stagePoint() itself.",
    cases,
  };
}
