import * as THREE from 'three';

import { SeededRng } from '../../src/sim/Playbook.ts';
import {
  FIXED_DT,
  createDiscState,
  simulate,
  throwDisc,
} from '../../src/sim/DiscPhysics.ts';
import { THROW_SPECS, THROW_TYPES, throwSpeed, throwSpinRate } from '../../src/sim/aero/Throws.ts';
import {
  AERO,
  DISC,
  dragCoeff,
  liftCoeff,
  pitchCoeff,
  reverseBlend,
  stallBlend,
  zeroLiftAlpha,
} from '../../src/sim/aero/Coeffs.ts';

/* ------------------------------------------------------------------- rng */

/**
 * The RNG's full observable surface, per seed.
 *
 * `next` is dumped as the raw uint32 state as well as the float it returns:
 * the float is what callers see, but the state is what a porting bug shows up
 * in first, and comparing only the float would hide a divergence that has not
 * yet reached the mantissa.
 */
export function rngGoldens() {
  const SEEDS = [0, 1, 7, 42, 0x9e3779b9, 0xdeadbeef, 2 ** 31, 4294967295];
  const cases = SEEDS.map((seed) => {
    const r = new SeededRng(seed);
    const next: number[] = [];
    for (let i = 0; i < 64; i++) next.push(r.next());

    // A fresh generator per derived call, so each sequence is independent of
    // how many draws the ones above it happened to consume.
    const range = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.range(-3.5, 12.25));
    })();
    const int = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.int(0, 6));
    })();
    const gauss = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.gauss());
    })();
    const forks = [0, 1, 2, 17, 1000, 0x7fffffff].map((salt) => {
      const g = new SeededRng(seed);
      const child = g.fork(salt);
      return { salt, next: Array.from({ length: 8 }, () => child.next()) };
    });

    return { seed, next, range, int, gauss, forks };
  });

  return {
    note:
      'Generated by tools/gen-goldens.ts from src/sim/Playbook.ts SeededRng. ' +
      'The RNG must port bit-exact; see swift/Sources/SimChecks/RngTests.swift.',
    cases,
  };
}
