import * as THREE from 'three';

import { SeededRng } from '../../src/sim/Playbook.ts';
import {
  FIXED_DT,
  createDiscState,
  simulate,
  throwDisc,
} from '../../src/sim/DiscPhysics.ts';
import { THROW_SPECS, THROW_TYPES, throwSpeed, throwSpinRate } from '../../src/sim/aero/Throws.ts';
import {
  AERO,
  DISC,
  dragCoeff,
  liftCoeff,
  pitchCoeff,
  reverseBlend,
  stallBlend,
  zeroLiftAlpha,
} from '../../src/sim/aero/Coeffs.ts';

/* --------------------------------------------------------------- simmath */

/**
 * Vector and quaternion algebra, as three.js actually implements it.
 *
 * The sim uses Three as a *math library*, so `Vec3d`/`Quatd` in Swift have to
 * agree with `THREE.Vector3`/`THREE.Quaternion` operation-for-operation, not
 * merely be correct. Every op here is `+ - * /` and `sqrt`, all correctly
 * rounded by IEEE 754, so the Swift side is asserted BIT-EXACT — any difference
 * is a transcription error in the operation order.
 *
 * `applyQuaternion` is the one that matters. It is the hot operation in the
 * derivative (disc normal, body axis, world angular velocity, body-frame torque)
 * and it is written as `v + w*t + cross(q.xyz, t)` with `t = 2*cross(q.xyz, v)`.
 * The algebraically equal `q*v*q⁻¹` rounds differently, so a "cleaner" Swift
 * implementation would drift from the reference in the fourth decimal after a
 * few hundred integration steps and look like a physics bug.
 */
export function simMathGoldens() {
  const rng = new SeededRng(0x5eed_c0de);

  const randVec = () => new THREE.Vector3(rng.range(-20, 20), rng.range(-20, 20), rng.range(-20, 20));
  const randQuat = () =>
    new THREE.Quaternion()
      .setFromAxisAngle(randVec().normalize(), rng.range(-Math.PI, Math.PI))
      .normalize();

  const edgeVecs: THREE.Vector3[] = [
    new THREE.Vector3(0, 0, 0),
    new THREE.Vector3(1, 0, 0),
    new THREE.Vector3(0, 1, 0),
    new THREE.Vector3(0, 0, 1),
    new THREE.Vector3(-1, -1, -1),
    // Tiny and huge, to catch anything that normalises with a bad epsilon.
    new THREE.Vector3(1e-9, 0, 0),
    new THREE.Vector3(1e8, -1e8, 1e8),
  ];
  const edgeQuats: THREE.Quaternion[] = [
    new THREE.Quaternion(0, 0, 0, 1), // identity
    new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI),
    new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 0, 1), Math.PI / 2),
  ];

  const pairs: { v: number[]; q: number[] }[] = [];
  for (const v of edgeVecs) for (const q of edgeQuats) {
    pairs.push({ v: [v.x, v.y, v.z], q: [q.x, q.y, q.z, q.w] });
  }
  for (let i = 0; i < 200; i++) {
    const v = randVec(), q = randQuat();
    pairs.push({ v: [v.x, v.y, v.z], q: [q.x, q.y, q.z, q.w] });
  }

  const cases = pairs.map(({ v, q }) => {
    const V = new THREE.Vector3(v[0], v[1], v[2]);
    const Q = new THREE.Quaternion(q[0], q[1], q[2], q[3]);
    const other = new THREE.Vector3(v[2] + 1.5, v[0] - 2.25, v[1] * 0.5);

    const applied = V.clone().applyQuaternion(Q);
    const conj = Q.clone().conjugate();
    const appliedConj = V.clone().applyQuaternion(conj);
    const normalized = V.clone().normalize();
    const scaled = V.clone().multiplyScalar(-3.75);
    const scaledAdd = V.clone().addScaledVector(other, 2.5);
    const crossed = new THREE.Vector3().crossVectors(V, other);

    return {
      v, q,
      other: [other.x, other.y, other.z],
      length: V.length(),
      lengthSq: V.lengthSq(),
      dot: V.dot(other),
      // The 4-argument hypot in `normQuat`. Kept as its own field because it is
      // one of only two non-planar hypot calls in the sim and cannot be swapped
      // for a bit-exact sqrt the way the 2-argument ones can.
      quatNorm: Math.hypot(q[0], q[1], q[2], q[3]),
      applyQuaternion: [applied.x, applied.y, applied.z],
      applyConjugate: [appliedConj.x, appliedConj.y, appliedConj.z],
      conjugate: [conj.x, conj.y, conj.z, conj.w],
      normalize: [normalized.x, normalized.y, normalized.z],
      multiplyScalar: [scaled.x, scaled.y, scaled.z],
      addScaledVector: [scaledAdd.x, scaledAdd.y, scaledAdd.z],
      crossVectors: [crossed.x, crossed.y, crossed.z],
    };
  });

  return {
    note:
      'Generated by tools/gen-goldens.ts against three.js r185. Every op is +-*/ and ' +
      'sqrt, so all of it must port BIT-EXACT. applyQuaternion must keep three.js ' +
      'operation order: t = 2*cross(q.xyz,v), then v + w*t + cross(q.xyz,t).',
    cases,
  };
}
