import * as THREE from 'three';

import { SeededRng } from '../../src/sim/Playbook.ts';
import {
  FIXED_DT,
  createDiscState,
  simulate,
  throwDisc,
} from '../../src/sim/DiscPhysics.ts';
import { THROW_SPECS, THROW_TYPES, throwSpeed, throwSpinRate } from '../../src/sim/aero/Throws.ts';
import {
  AERO,
  DISC,
  dragCoeff,
  liftCoeff,
  pitchCoeff,
  reverseBlend,
  stallBlend,
  zeroLiftAlpha,
} from '../../src/sim/aero/Coeffs.ts';

/* ------------------------------------------------------------------ throws */

/**
 * The real throw table, and the release states `throwDisc` builds from it.
 *
 * This is the fixture that would have caught my hand-set presets being wrong:
 * a backhand and a forehand differ by `spinSign`, not by bank, so any port that
 * only varies the bank angle produces two throws that curve the same way. Each
 * type is flown for four seconds at three power levels and both handednesses,
 * because handedness mirrors both the spin sign AND the bank and getting one of
 * the two mirrors wrong is invisible in a right-handed-only fixture.
 */
export function throwGoldens() {
  const cases: unknown[] = [];

  for (const type of THROW_TYPES) {
    for (const hand of ['R', 'L'] as const) {
      for (const power of [0, 0.5, 1]) {
        const s = throwDisc(
          type,
          new THREE.Vector3(0, 1.6, 0),
          new THREE.Vector3(1, 0, 0),
          power, 0, 0.5,
          { hand },
        );
        const release = {
          pos: [s.pos.x, s.pos.y, s.pos.z],
          vel: [s.vel.x, s.vel.y, s.vel.z],
          orient: [s.orient.x, s.orient.y, s.orient.z, s.orient.w],
          omega: [s.omega.x, s.omega.y, s.omega.z],
          alpha: s.alpha, spin: s.spin, airspeed: s.airspeed,
        };

        const samples: unknown[] = [];
        for (let i = 0; i < 480; i++) {
          simulate(s, FIXED_DT);
          if ((i + 1) % 12 === 0) {
            samples.push({ t: s.t, pos: [s.pos.x, s.pos.y, s.pos.z], atRest: s.atRest });
          }
        }

        cases.push({ type, hand, power, release, samples });
      }
    }
  }

  return {
    note:
      'Generated by tools/gen-goldens.ts from src/sim/aero/Throws.ts and throwDisc. ' +
      'Release states are asserted tightly; flights use the horizon tolerance.',
    specs: Object.fromEntries(THROW_TYPES.map((t) => [t, {
      ...THROW_SPECS[t],
      speedAt: [throwSpeed(t, 0), throwSpeed(t, 0.5), throwSpeed(t, 1)],
      spinAt: [throwSpinRate(t, 0), throwSpinRate(t, 0.5), throwSpinRate(t, 1)],
    }])),
    cases,
  };
}
