/**
 * Golden-vector generator for the Swift port.
 *
 *   node tools/gen-goldens.ts
 *
 * Writes JSON fixtures under `swift/Tests/UltimateSimTests/Goldens/`. The Swift
 * sim is validated against these rather than against a re-reading of the
 * TypeScript by a human, because the whole risk of this port is silent
 * behavioural drift that reads correctly on the page.
 *
 * The rule for what belongs here: anything whose contract is a *number*. The
 * RNG must match bit-for-bit — it is the anchor, and divergence there means a
 * structural porting bug rather than numeric drift. Continuous state matches
 * within a tolerance the consuming test states for itself.
 *
 * These files are generated, committed, and read-only to the Swift side. When a
 * fixture changes, the diff is the record of a deliberate behaviour change.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

import { SeededRng } from '../src/sim/Playbook.ts';

const OUT = join(import.meta.dirname, '..', 'swift', 'Goldens');

function write(name: string, data: unknown): void {
  const path = join(OUT, name);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(data, null, 2) + '\n');
  console.log(`  ${name}`);
}

/* ------------------------------------------------------------------- rng */

/**
 * The RNG's full observable surface, per seed.
 *
 * `next` is dumped as the raw uint32 state as well as the float it returns:
 * the float is what callers see, but the state is what a porting bug shows up
 * in first, and comparing only the float would hide a divergence that has not
 * yet reached the mantissa.
 */
function rngGoldens() {
  const SEEDS = [0, 1, 7, 42, 0x9e3779b9, 0xdeadbeef, 2 ** 31, 4294967295];
  const cases = SEEDS.map((seed) => {
    const r = new SeededRng(seed);
    const next: number[] = [];
    for (let i = 0; i < 64; i++) next.push(r.next());

    // A fresh generator per derived call, so each sequence is independent of
    // how many draws the ones above it happened to consume.
    const range = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.range(-3.5, 12.25));
    })();
    const int = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.int(0, 6));
    })();
    const gauss = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.gauss());
    })();
    const forks = [0, 1, 2, 17, 1000, 0x7fffffff].map((salt) => {
      const g = new SeededRng(seed);
      const child = g.fork(salt);
      return { salt, next: Array.from({ length: 8 }, () => child.next()) };
    });

    return { seed, next, range, int, gauss, forks };
  });

  return {
    note:
      'Generated by tools/gen-goldens.ts from src/sim/Playbook.ts SeededRng. ' +
      'The RNG must port bit-exact; see swift/Tests/UltimateSimTests/RngTests.swift.',
    cases,
  };
}

/* ------------------------------------------------------------------- main */

console.log('goldens →');
write('rng.json', rngGoldens());
console.log('done');
