/**
 * Golden-vector generator for the Swift port.
 *
 *   node tools/gen-goldens.ts
 *
 * Writes JSON fixtures under `swift/Sources/SimChecks/Goldens/`, which ship as
 * a resource bundle so the same checks run on device as in the terminal. The Swift
 * sim is validated against these rather than against a re-reading of the
 * TypeScript by a human, because the whole risk of this port is silent
 * behavioural drift that reads correctly on the page.
 *
 * The rule for what belongs here: anything whose contract is a *number*. The
 * RNG must match bit-for-bit — it is the anchor, and divergence there means a
 * structural porting bug rather than numeric drift. Continuous state matches
 * within a tolerance the consuming test states for itself.
 *
 * These files are generated, committed, and read-only to the Swift side. When a
 * fixture changes, the diff is the record of a deliberate behaviour change.
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';

import * as THREE from 'three';

import { SeededRng } from '../src/sim/Playbook.ts';
import {
  AERO,
  DISC,
  dragCoeff,
  liftCoeff,
  pitchCoeff,
  reverseBlend,
  stallBlend,
  zeroLiftAlpha,
} from '../src/sim/aero/Coeffs.ts';

const OUT = join(import.meta.dirname, '..', 'swift', 'Sources', 'SimChecks', 'Goldens');

function write(name: string, data: unknown): void {
  const path = join(OUT, name);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(data, null, 2) + '\n');
  console.log(`  ${name}`);
}

/* ------------------------------------------------------------------- rng */

/**
 * The RNG's full observable surface, per seed.
 *
 * `next` is dumped as the raw uint32 state as well as the float it returns:
 * the float is what callers see, but the state is what a porting bug shows up
 * in first, and comparing only the float would hide a divergence that has not
 * yet reached the mantissa.
 */
function rngGoldens() {
  const SEEDS = [0, 1, 7, 42, 0x9e3779b9, 0xdeadbeef, 2 ** 31, 4294967295];
  const cases = SEEDS.map((seed) => {
    const r = new SeededRng(seed);
    const next: number[] = [];
    for (let i = 0; i < 64; i++) next.push(r.next());

    // A fresh generator per derived call, so each sequence is independent of
    // how many draws the ones above it happened to consume.
    const range = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.range(-3.5, 12.25));
    })();
    const int = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.int(0, 6));
    })();
    const gauss = (() => {
      const g = new SeededRng(seed);
      return Array.from({ length: 16 }, () => g.gauss());
    })();
    const forks = [0, 1, 2, 17, 1000, 0x7fffffff].map((salt) => {
      const g = new SeededRng(seed);
      const child = g.fork(salt);
      return { salt, next: Array.from({ length: 8 }, () => child.next()) };
    });

    return { seed, next, range, int, gauss, forks };
  });

  return {
    note:
      'Generated by tools/gen-goldens.ts from src/sim/Playbook.ts SeededRng. ' +
      'The RNG must port bit-exact; see swift/Sources/SimChecks/RngTests.swift.',
    cases,
  };
}

/* ---------------------------------------------------------------- coeffs */

/**
 * The coefficient curves, sampled across the full alpha domain.
 *
 * The sweep is dense and uniform so nothing is cherry-picked, but the named
 * angles matter more than the sweep does: they sit exactly on the boundaries
 * where the curves are piecewise — the stall blend's two ends, the zero-lift
 * angle, the far end of the reversal — and a port that gets the smoothstep
 * clamping subtly wrong passes a coarse sweep and fails precisely there.
 */
function coeffGoldens() {
  const z = zeroLiftAlpha(AERO);

  const named: Record<string, number> = {
    zero: 0,
    zeroLift: z,
    // Both sides of each piecewise boundary, since a `<=` written as `<`
    // (or a clamp applied one step late) only shows up on one side.
    stallStart: AERO.aStall,
    stallStartBelow: AERO.aStall - 1e-9,
    stallEnd: AERO.aStall + AERO.aStallWidth,
    stallEndAbove: AERO.aStall + AERO.aStallWidth + 1e-9,
    stallMid: AERO.aStall + AERO.aStallWidth / 2,
    revStart: z - 1e-9,
    revEnd: z - AERO.revWidth,
    revEndBelow: z - AERO.revWidth - 1e-9,
    revMid: z - AERO.revWidth / 2,
    trim: -AERO.CM0 / AERO.CMa, // near the zero-moment angle
    quarterPi: Math.PI / 4,
    halfPi: Math.PI / 2,
    pi: Math.PI,
    negHalfPi: -Math.PI / 2,
    negPi: -Math.PI,
  };

  // 361 samples, one per half-degree over the full domain.
  const sweep: number[] = [];
  for (let i = 0; i <= 360; i++) sweep.push(-Math.PI + (i / 360) * 2 * Math.PI);

  const sample = (alpha: number) => ({
    alpha,
    stallBlend: stallBlend(alpha, AERO),
    reverseBlend: reverseBlend(alpha, AERO),
    lift: liftCoeff(alpha, AERO),
    drag: dragCoeff(alpha, AERO),
    pitch: pitchCoeff(alpha, AERO),
  });

  return {
    note:
      'Generated by tools/gen-goldens.ts from src/sim/aero/Coeffs.ts. ' +
      'stallBlend and reverseBlend are pure arithmetic and must port bit-exact; ' +
      'lift, drag and pitch call sin/tanh and get a tolerance.',
    disc: DISC,
    aero: AERO,
    zeroLiftAlpha: z,
    named: Object.fromEntries(
      Object.entries(named).map(([k, alpha]) => [k, sample(alpha)]),
    ),
    sweep: sweep.map(sample),
  };
}

/* --------------------------------------------------------------- simmath */

/**
 * Vector and quaternion algebra, as three.js actually implements it.
 *
 * The sim uses Three as a *math library*, so `Vec3d`/`Quatd` in Swift have to
 * agree with `THREE.Vector3`/`THREE.Quaternion` operation-for-operation, not
 * merely be correct. Every op here is `+ - * /` and `sqrt`, all correctly
 * rounded by IEEE 754, so the Swift side is asserted BIT-EXACT — any difference
 * is a transcription error in the operation order.
 *
 * `applyQuaternion` is the one that matters. It is the hot operation in the
 * derivative (disc normal, body axis, world angular velocity, body-frame torque)
 * and it is written as `v + w*t + cross(q.xyz, t)` with `t = 2*cross(q.xyz, v)`.
 * The algebraically equal `q*v*q⁻¹` rounds differently, so a "cleaner" Swift
 * implementation would drift from the reference in the fourth decimal after a
 * few hundred integration steps and look like a physics bug.
 */
function simMathGoldens() {
  const rng = new SeededRng(0x5eed_c0de);

  const randVec = () => new THREE.Vector3(rng.range(-20, 20), rng.range(-20, 20), rng.range(-20, 20));
  const randQuat = () =>
    new THREE.Quaternion()
      .setFromAxisAngle(randVec().normalize(), rng.range(-Math.PI, Math.PI))
      .normalize();

  const edgeVecs: THREE.Vector3[] = [
    new THREE.Vector3(0, 0, 0),
    new THREE.Vector3(1, 0, 0),
    new THREE.Vector3(0, 1, 0),
    new THREE.Vector3(0, 0, 1),
    new THREE.Vector3(-1, -1, -1),
    // Tiny and huge, to catch anything that normalises with a bad epsilon.
    new THREE.Vector3(1e-9, 0, 0),
    new THREE.Vector3(1e8, -1e8, 1e8),
  ];
  const edgeQuats: THREE.Quaternion[] = [
    new THREE.Quaternion(0, 0, 0, 1), // identity
    new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(1, 0, 0), Math.PI),
    new THREE.Quaternion().setFromAxisAngle(new THREE.Vector3(0, 0, 1), Math.PI / 2),
  ];

  const pairs: { v: number[]; q: number[] }[] = [];
  for (const v of edgeVecs) for (const q of edgeQuats) {
    pairs.push({ v: [v.x, v.y, v.z], q: [q.x, q.y, q.z, q.w] });
  }
  for (let i = 0; i < 200; i++) {
    const v = randVec(), q = randQuat();
    pairs.push({ v: [v.x, v.y, v.z], q: [q.x, q.y, q.z, q.w] });
  }

  const cases = pairs.map(({ v, q }) => {
    const V = new THREE.Vector3(v[0], v[1], v[2]);
    const Q = new THREE.Quaternion(q[0], q[1], q[2], q[3]);
    const other = new THREE.Vector3(v[2] + 1.5, v[0] - 2.25, v[1] * 0.5);

    const applied = V.clone().applyQuaternion(Q);
    const conj = Q.clone().conjugate();
    const appliedConj = V.clone().applyQuaternion(conj);
    const normalized = V.clone().normalize();
    const scaled = V.clone().multiplyScalar(-3.75);
    const scaledAdd = V.clone().addScaledVector(other, 2.5);
    const crossed = new THREE.Vector3().crossVectors(V, other);

    return {
      v, q,
      other: [other.x, other.y, other.z],
      length: V.length(),
      lengthSq: V.lengthSq(),
      dot: V.dot(other),
      // The 4-argument hypot in `normQuat`. Kept as its own field because it is
      // one of only two non-planar hypot calls in the sim and cannot be swapped
      // for a bit-exact sqrt the way the 2-argument ones can.
      quatNorm: Math.hypot(q[0], q[1], q[2], q[3]),
      applyQuaternion: [applied.x, applied.y, applied.z],
      applyConjugate: [appliedConj.x, appliedConj.y, appliedConj.z],
      conjugate: [conj.x, conj.y, conj.z, conj.w],
      normalize: [normalized.x, normalized.y, normalized.z],
      multiplyScalar: [scaled.x, scaled.y, scaled.z],
      addScaledVector: [scaledAdd.x, scaledAdd.y, scaledAdd.z],
      crossVectors: [crossed.x, crossed.y, crossed.z],
    };
  });

  return {
    note:
      'Generated by tools/gen-goldens.ts against three.js r185. Every op is +-*/ and ' +
      'sqrt, so all of it must port BIT-EXACT. applyQuaternion must keep three.js ' +
      'operation order: t = 2*cross(q.xyz,v), then v + w*t + cross(q.xyz,t).',
    cases,
  };
}

/* ------------------------------------------------------------------- main */

console.log('goldens →');
write('rng.json', rngGoldens());
write('coeffs.json', coeffGoldens());
write('simmath.json', simMathGoldens());
console.log('done');
