import * as THREE from 'three';
import { canvasTexture } from '../../util/Tex';
import type { Ctx } from '../../core/Ctx';
import { Mesher, parts, mat, strut, UNIT_BOX, type Part, type RGB } from './Geo';
import type { StadiumMaterials } from './Materials';
import { SeatMapSampler } from './Materials';
import {
  BOWL, BASE_PERIMETER, AISLES, AISLE_HALF, VOMS,
  rowY, rowRise, rowOffset, perimeterAt, walkRow, ptAt, type RingPt,
} from './Layout';

/**
 * The seating bowl: raked concrete deck, seats, aisles, stairs, handrails,
 * vomitories and signage.
 *
 * The whole deck is one welded ribbon. Rows are exact outward offsets of the
 * plan outline, so a row is generated by pushing every outline sample along its
 * own normal — corners stay concentric and the rake stays continuous through
 * them. Rake steepens with row (riser height lerps 0.27 m → 0.66 m front to
 * back), which is what gives a real bowl its dished profile and keeps sightlines
 * clear over the row in front.
 */

interface VomBand { t: number; r0: number; r1: number; halfT: number }

const _p: RingPt = { x: 0, z: 0, nx: 0, nz: 0, t: 0, seg: 0 };

export interface BowlBuild {
  group: THREE.Group;
  seatCount: number;
}

export function buildBowl(ctx: Ctx, M: StadiumMaterials, rows: number, ringN: number): BowlBuild {
  const g = new THREE.Group();
  g.name = 'bowl';

  const topY = rowY(rows, rows);
  const outerOff = rowOffset(rows);
  const concourseW = 3.4;
  const hi = ctx.quality.tier === 'high' || ctx.quality.tier === 'ultra';

  /* ------------------------------------------------------------ vom bands */
  const voms: VomBand[] = VOMS.map((v) => ({
    t: AISLES[v.aisle % AISLES.length],
    r0: v.row0,
    r1: Math.min(rows - 3, v.row0 + v.span),
    halfT: v.halfW / perimeterAt(rowOffset(v.row0)),
  })).filter((v) => v.r1 > v.r0 + 2);

  const dT = (a: number, b: number) => { const d = Math.abs(a - b); return d > 0.5 ? 1 - d : d; };
  const vomAt = (t: number, r: number): VomBand | null => {
    for (const v of voms) if (r >= v.r0 && r < v.r1 && dT(t, v.t) < v.halfT) return v;
    return null;
  };
  const aisleAt = (t: number, off: number): boolean => {
    const half = AISLE_HALF / perimeterAt(off);
    for (const a of AISLES) if (dT(t, a) < half) return true;
    return false;
  };

  /* ----------------------------------------------------------- ring cache */
  const ring: RingPt[] = [];
  for (let i = 0; i <= ringN; i++) {
    const p: RingPt = { x: 0, z: 0, nx: 0, nz: 0, t: 0, seg: 0 };
    ptAt((i / ringN) % 1, 0, p);
    p.t = i / ringN;
    ring.push(p);
  }
  const A: [number, number] = [0, 0], B: [number, number] = [0, 0];
  const C: [number, number] = [0, 0], D: [number, number] = [0, 0];
  const at = (i: number, off: number, out: [number, number]) => {
    const p = ring[Math.min(ringN, Math.max(0, i))];
    out[0] = p.x + p.nx * off; out[1] = p.z + p.nz * off;
  };
  const US = 0.29;  // world metres → texture repeats

  /* ============================================================ deck mesh */
  const deck = new Mesher();
  const uAt = (i: number) => ring[Math.min(ringN, i)].t * BASE_PERIMETER * US;

  // Pitch-side perimeter wall (LED boards hang on this) + front gangway.
  for (let i = 0; i < ringN; i++) {
    const u0 = uAt(i), u1 = uAt(i + 1), wy = BOWL.firstRowY;
    at(i, 0, A); at(i + 1, 0, B);
    deck.quad([A[0], 0, A[1]], [B[0], 0, B[1]], [B[0], wy, B[1]], [A[0], wy, A[1]],
      [u0, 0, u1, 0, u1, wy * US, u0, wy * US], [0.5, 0.5, 1, 1]);
    at(i + 1, rowOffset(0), C); at(i, rowOffset(0), D);
    deck.quad([A[0], wy, A[1]], [B[0], wy, B[1]], [C[0], wy, C[1]], [D[0], wy, D[1]],
      [u0, 0, u1, 0, u1, rowOffset(0) * US, u0, rowOffset(0) * US], [0.8, 0.8, 0.95, 0.95]);
  }

  // Treads + risers.
  let vAcc = rowOffset(0) * US;
  for (let r = 0; r < rows; r++) {
    const o0 = rowOffset(r), o1 = o0 + BOWL.rowDepth;
    const rise = rowRise(r, rows);
    const y0 = rowY(r, rows), y1 = y0 + rise;
    const vT0 = vAcc, vT1 = vAcc + BOWL.rowDepth * US, vR1 = vT1 + rise * US;
    vAcc = vR1;
    for (let i = 0; i < ringN; i++) {
      const tm = (ring[i].t + ring[i + 1].t) * 0.5;
      if (vomAt(tm, r)) continue;
      const u0 = uAt(i), u1 = uAt(i + 1);
      at(i, o0, A); at(i + 1, o0, B); at(i + 1, o1, C); at(i, o1, D);
      deck.quad([A[0], y0, A[1]], [B[0], y0, B[1]], [C[0], y0, C[1]], [D[0], y0, D[1]],
        [u0, vT0, u1, vT0, u1, vT1, u0, vT1], [0.98, 0.98, 0.62, 0.62]);
      deck.quad([D[0], y0, D[1]], [C[0], y0, C[1]], [C[0], y1, C[1]], [D[0], y1, D[1]],
        [u0, vT1, u1, vT1, u1, vR1, u0, vR1], [0.5, 0.5, 1.0, 1.0]);
    }
  }

  // Top concourse deck, parapet and the outer skirt down to grade.
  for (let i = 0; i < ringN; i++) {
    const u0 = uAt(i), u1 = uAt(i + 1);
    at(i, outerOff, A); at(i + 1, outerOff, B);
    at(i + 1, outerOff + concourseW, C); at(i, outerOff + concourseW, D);
    deck.quad([A[0], topY, A[1]], [B[0], topY, B[1]], [C[0], topY, C[1]], [D[0], topY, D[1]],
      [u0, 0, u1, 0, u1, concourseW * US, u0, concourseW * US], [0.7, 0.7, 0.92, 0.92]);
    const pO = outerOff + concourseW, pT = topY + 1.15;
    at(i, pO, A); at(i + 1, pO, B); at(i + 1, pO + 0.3, C); at(i, pO + 0.3, D);
    deck.quad([A[0], topY, A[1]], [B[0], topY, B[1]], [B[0], pT, B[1]], [A[0], pT, A[1]],
      [u0, 0, u1, 0, u1, 1.15 * US, u0, 1.15 * US], [0.68, 0.68, 1, 1]);
    deck.quad([A[0], pT, A[1]], [B[0], pT, B[1]], [C[0], pT, C[1]], [D[0], pT, D[1]],
      [u0, 0, u1, 0, u1, 0.3 * US, u0, 0.3 * US], [1, 1, 1, 1]);
    deck.quad([C[0], 0, C[1]], [D[0], 0, D[1]], [D[0], pT, D[1]], [C[0], pT, C[1]],
      [u1, 0, u0, 0, u0, pT * US, u1, pT * US], [0.45, 0.45, 0.95, 0.95]);
  }

  const deckMesh = new THREE.Mesh(deck.build('bowl-deck'), M.concrete);
  deckMesh.castShadow = true; deckMesh.receiveShadow = true;
  g.add(deckMesh);

  /* --------------------------------------------------------- vomitories */
  const vomM = new Mesher();
  for (const v of voms) {
    const yF = rowY(v.r0, rows);
    const oIn = rowOffset(v.r0), oOut = rowOffset(v.r1);
    const iA = Math.max(0, Math.round((v.t - v.halfT) * ringN));
    const iB = Math.min(ringN, Math.round((v.t + v.halfT) * ringN));
    if (iB <= iA) continue;
    const head = Math.min(rowY(v.r1, rows) - 0.25, yF + 2.7);
    const depth = 8.0;

    for (let i = iA; i < iB; i++) {
      const u0 = uAt(i), u1 = uAt(i + 1);
      // landing slab
      at(i, oIn, A); at(i + 1, oIn, B); at(i + 1, oOut, C); at(i, oOut, D);
      vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [C[0], yF, C[1]], [D[0], yF, D[1]],
        [u0, 0, u1, 0, u1, (oOut - oIn) * US, u0, (oOut - oIn) * US], [0.75, 0.75, 0.5, 0.5]);
      // tunnel ceiling / floor / back wall
      at(i, oOut, A); at(i + 1, oOut, B); at(i, oOut + depth, C); at(i + 1, oOut + depth, D);
      vomM.quad([A[0], head, A[1]], [B[0], head, B[1]], [D[0], head, D[1]], [C[0], head, C[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.12, 0.12, 0.03, 0.03]);
      vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [D[0], yF, D[1]], [C[0], yF, C[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.28, 0.28, 0.05, 0.05]);
      vomM.quad([C[0], yF, C[1]], [D[0], yF, D[1]], [D[0], head, D[1]], [C[0], head, C[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.05, 0.05, 0.03, 0.03]);
      // lintel across the top of the mouth
      vomM.quad([A[0], head, A[1]], [B[0], head, B[1]], [B[0], rowY(v.r1, rows), B[1]], [A[0], rowY(v.r1, rows), A[1]],
        [u0, 0, u1, 0, u1, 0.3, u0, 0.3], [0.55, 0.55, 0.85, 0.85]);
    }
    // stepped side walls of the cut + tunnel side walls
    for (const side of [iA, iB]) {
      for (let r = v.r0; r < v.r1; r++) {
        const o0 = rowOffset(r), o1 = o0 + BOWL.rowDepth;
        const y = rowY(r, rows) + rowRise(r, rows);
        at(side, o0, A); at(side, o1, B);
        const uu = r * BOWL.rowDepth * US, uu1 = uu + BOWL.rowDepth * US, vv = (y - yF) * US;
        vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [B[0], y, B[1]], [A[0], y, A[1]],
          [uu, 0, uu1, 0, uu1, vv, uu, vv], [0.45, 0.45, 0.9, 0.9]);
      }
      at(side, oOut, A); at(side, oOut + depth, B);
      vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [B[0], head, B[1]], [A[0], head, A[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.1, 0.1, 0.06, 0.06]);
    }
  }
  const vomMesh = new THREE.Mesh(vomM.build('bowl-voms'), M.concreteDark);
  vomMesh.receiveShadow = true;
  g.add(vomMesh);

  /* ============================================================== aisles */
  // Each seating row splits into two shallower steps inside the aisle, with a
  // painted nosing on every step. Lifted 2 cm off the deck to avoid z-fighting.
  const stair = new Mesher();
  const railParts: Part[] = [];
  const NOSE: RGB = [2.1, 1.9, 0.95];
  const STEP: RGB = [1.16, 1.16, 1.13];
  const LIFT = 0.02;

  for (const aT of AISLES) {
    ptAt(aT, 0, _p);
    const nx = _p.nx, nz = _p.nz, tx = -nz, tz = nx;
    const bx = _p.x, bz = _p.z, hw = AISLE_HALF;

    for (let r = 0; r < rows; r++) {
      if (vomAt(aT, r)) continue;
      const o0 = rowOffset(r), rise = rowRise(r, rows), y0 = rowY(r, rows) + LIFT;
      for (let s = 0; s < 2; s++) {
        const so = o0 + s * BOWL.rowDepth * 0.5;
        const sy = y0 + s * rise * 0.5;
        const d = BOWL.rowDepth * 0.5 - 0.012;
        const ax = bx + nx * so, az = bz + nz * so;
        const cx = bx + nx * (so + d), cz = bz + nz * (so + d);
        stair.quad(
          [ax - tx * hw, sy, az - tz * hw], [ax + tx * hw, sy, az + tz * hw],
          [cx + tx * hw, sy, cz + tz * hw], [cx - tx * hw, sy, cz - tz * hw],
          [0, 0, 1, 0, 1, 1, 0, 1], [1, 1, 0.74, 0.74], STEP);
        const ex = bx + nx * (so + d - 0.06), ez = bz + nz * (so + d - 0.06);
        stair.quad(
          [ex - tx * hw, sy + 0.006, ez - tz * hw], [ex + tx * hw, sy + 0.006, ez + tz * hw],
          [cx + tx * hw, sy + 0.006, cz + tz * hw], [cx - tx * hw, sy + 0.006, cz - tz * hw],
          [0, 0, 1, 0, 1, 1, 0, 1], [1, 1, 1, 1], NOSE);
        stair.quad(
          [cx - tx * hw, sy, cz - tz * hw], [cx + tx * hw, sy, cz + tz * hw],
          [cx + tx * hw, sy + rise * 0.5, cz + tz * hw], [cx - tx * hw, sy + rise * 0.5, cz - tz * hw],
          [0, 0, 1, 0, 1, 1, 0, 1], [0.62, 0.62, 1, 1], STEP);
      }
    }

    // Handrails: one either side of the aisle, 1.0 m above the nosing line.
    const railStep = 3;
    for (const sgn of [-1, 1]) {
      const ox = bx + tx * sgn * (hw + 0.05), oz = bz + tz * sgn * (hw + 0.05);
      for (let r = 0; r < rows; r += railStep) {
        const r2 = Math.min(rows, r + railStep);
        const o1 = rowOffset(r) + BOWL.rowDepth * 0.5, o2 = rowOffset(r2) + BOWL.rowDepth * 0.5;
        const p1: [number, number, number] = [ox + nx * o1, rowY(r, rows) + 1.02, oz + nz * o1];
        const p2: [number, number, number] = [ox + nx * o2, rowY(r2, rows) + 1.02, oz + nz * o2];
        railParts.push(strut(p1, p2, 0.055, UNIT_BOX));
        railParts.push(strut([p1[0], rowY(r, rows), p1[2]], p1, 0.05, UNIT_BOX));
      }
    }
  }

  const stairMesh = new THREE.Mesh(stair.build('bowl-stairs'), M.concrete);
  stairMesh.receiveShadow = true;
  g.add(stairMesh);

  const railMesh = new THREE.Mesh(parts(railParts, 'bowl-rails'), M.steel);
  railMesh.castShadow = hi;
  railMesh.receiveShadow = true;
  g.add(railMesh);

  /* =============================================================== seats */
  const seatGeo = buildSeatGeometry(hi);
  const sampler = new SeatMapSampler();

  const slots: { x: number; y: number; z: number; yaw: number; t: number; r: number }[] = [];
  for (let r = 0; r < rows; r++) {
    const off = rowOffset(r) + BOWL.rowDepth * 0.60;
    const y = rowY(r, rows);
    walkRow(off, BOWL.seatPitch, (x, z, nx, nz, t) => {
      if (aisleAt(t, off) || vomAt(t, r)) return;
      slots.push({ x, y, z, yaw: Math.atan2(-nx, -nz), t, r });
    });
  }

  const seats = new THREE.InstancedMesh(seatGeo, M.seat, slots.length);
  seats.name = 'seats';
  {
    const m4 = new THREE.Matrix4();
    const q = new THREE.Quaternion();
    const e = new THREE.Euler();
    const sc = new THREE.Vector3(1, 1, 1);
    const v3 = new THREE.Vector3();
    const col = new THREE.Color();
    const jitter = ctx.rand.fork(0x5ea7);
    for (let i = 0; i < slots.length; i++) {
      const p = slots[i];
      e.set(0, p.yaw, 0);
      q.setFromEuler(e);
      v3.set(p.x, p.y, p.z);
      m4.compose(v3, q, sc);
      seats.setMatrixAt(i, m4);
      sampler.sample(p.t, rows > 1 ? p.r / (rows - 1) : 0, col);
      col.multiplyScalar(0.9 + jitter.next() * 0.2);
      seats.setColorAt(i, col);
    }
  }
  seats.instanceMatrix.needsUpdate = true;
  if (seats.instanceColor) seats.instanceColor.needsUpdate = true;
  seats.castShadow = hi;
  seats.receiveShadow = true;
  seats.frustumCulled = false;
  g.add(seats);

  /* ============================================================= signage */
  const signMat = M.signage.clone();
  signMat.map = bakeSignAtlas();
  signMat.name = 'signage';
  const sign = new Mesher();
  const cellU = 1 / 8, cellV = 1 / 12;
  const cellUV = (cell: number) => {
    const cx = cell % 8, cy = Math.floor(cell / 8);
    const u0 = cx * cellU, v1 = 1 - cy * cellV, v0 = v1 - cellV;
    return [u0, v0, u0 + cellU, v0, u0 + cellU, v1, u0, v1];
  };

  for (let a = 0; a < AISLES.length; a++) {
    ptAt(AISLES[a], 0, _p);
    const nx = _p.nx, nz = _p.nz, tx = -nz, tz = nx;
    const o = outerOff + concourseW + 0.35;
    const x = _p.x + nx * o, z = _p.z + nz * o, y = topY + 1.9;
    const w = 0.9, h = 0.6;
    sign.quad([x - tx * w, y - h, z - tz * w], [x + tx * w, y - h, z + tz * w],
      [x + tx * w, y + h, z + tz * w], [x - tx * w, y + h, z - tz * w], cellUV(a % 32));
  }
  for (const aT of AISLES) {
    ptAt(aT, 0, _p);
    const nx = _p.nx, nz = _p.nz, tx = -nz, tz = nx;
    for (let r = 0; r < rows; r++) {
      if (vomAt(aT, r)) continue;
      const o = rowOffset(r) + BOWL.rowDepth - 0.018;
      const y = rowY(r, rows) + LIFT + 0.03;
      const h = Math.min(0.2, rowRise(r, rows) * 0.62);
      const x = _p.x + nx * o, z = _p.z + nz * o;
      const cx = x - tx * (AISLE_HALF - 0.19), cz = z - tz * (AISLE_HALF - 0.19);
      const hw = 0.15;
      sign.quad([cx - tx * hw, y, cz - tz * hw], [cx + tx * hw, y, cz + tz * hw],
        [cx + tx * hw, y + h, cz + tz * hw], [cx - tx * hw, y + h, cz - tz * hw],
        cellUV(32 + (r % 64)));
    }
  }
  g.add(new THREE.Mesh(sign.build('bowl-signage'), signMat));

  return { group: g, seatCount: slots.length };
}

/* ------------------------------------------------------------------ seats */

/** Folding-style stadium seat: shell back, pan, pedestal, optional arms. */
function buildSeatGeometry(detailed: boolean): THREE.BufferGeometry {
  const list: Part[] = [
    { geo: UNIT_BOX, m: mat(0, 0.665, -0.175, -0.23, 0, 0, 0.455, 0.44, 0.055), color: [1, 1, 1], uvScale: 0.9 },
    { geo: UNIT_BOX, m: mat(0, 0.452, 0.045, -0.07, 0, 0, 0.455, 0.055, 0.42), color: [0.95, 0.95, 0.95], uvScale: 0.9 },
    { geo: UNIT_BOX, m: mat(0, 0.215, -0.055, 0, 0, 0, 0.16, 0.43, 0.10), color: [0.4, 0.4, 0.42] },
  ];
  if (detailed) {
    list.push(
      { geo: UNIT_BOX, m: mat(0.245, 0.545, -0.03, 0, 0, 0, 0.045, 0.11, 0.33), color: [0.74, 0.74, 0.75] },
      { geo: UNIT_BOX, m: mat(-0.245, 0.545, -0.03, 0, 0, 0, 0.045, 0.11, 0.33), color: [0.74, 0.74, 0.75] },
    );
  }
  return parts(list, 'seat');
}

/* ---------------------------------------------------------------- signage */

/** 8×12 atlas: cells 0..31 section plates "101"…"132", 32..95 row numbers. */
function bakeSignAtlas(): THREE.CanvasTexture {
  return canvasTexture(1024, 1024, (c, W, H) => {
    c.clearRect(0, 0, W, H);
    const cw = W / 8, ch = H / 12;
    c.textAlign = 'center';
    c.textBaseline = 'middle';
    for (let cell = 0; cell < 96; cell++) {
      const cx = (cell % 8) * cw, cy = Math.floor(cell / 8) * ch;
      if (cell < 32) {
        c.fillStyle = '#0d1c2c';
        c.fillRect(cx + 6, cy + 10, cw - 12, ch - 20);
        c.strokeStyle = '#d9a441';
        c.lineWidth = 3;
        c.strokeRect(cx + 6, cy + 10, cw - 12, ch - 20);
        c.fillStyle = '#f2f5f7';
        c.font = '700 42px "Helvetica Neue", Helvetica, Arial, sans-serif';
        c.fillText(String(101 + cell), cx + cw / 2, cy + ch / 2 + 6);
        c.font = '600 14px "Helvetica Neue", Helvetica, Arial, sans-serif';
        c.fillStyle = '#9fb4c6';
        c.fillText('SECTION', cx + cw / 2, cy + 24);
      } else {
        c.fillStyle = '#efe9d8';
        c.font = '800 44px "Helvetica Neue", Helvetica, Arial, sans-serif';
        c.fillText(String(cell - 31), cx + cw / 2, cy + ch / 2);
      }
    }
  }, { name: 'sign-atlas', anisotropy: 8 });
}
