import * as THREE from 'three';
import { canvasTexture } from '../../util/Tex';
import type { Ctx } from '../../core/Ctx';
import { Mesher, parts, mat, strut, UNIT_BOX, type Part, type RGB } from './Geo';
import type { StadiumMaterials } from './Materials';
import { SeatMapSampler } from './Materials';
import {
  BOWL, BASE_PERIMETER, AISLES, AISLE_COUNT, AISLE_HALF, VOMS, GATES,
  rowY, rowRise, rowOffset, rowTread, rowSeatDepth, isCrossAisleRow,
  perimeterAt, walkRow, ptAt, ringTable, sampleSeats, type RingPt,
} from './Layout';

/**
 * The seating bowl: raked concrete deck, seats, aisles, stairs, handrails,
 * vomitories, an outer facade and signage.
 *
 * The whole deck is one welded ribbon. Rows are exact outward offsets of the
 * plan outline, so a row is generated by pushing every outline sample along its
 * own normal — corners stay concentric and the rake stays continuous through
 * them.
 *
 * The rake is two-tier (see Layout.ts): a shallow lower tier, a cross-aisle
 * landing with a step up, then a distinctly steeper upper tier. That break is
 * what stops a big bowl reading as one undifferentiated ramp, and it is where
 * the vomitories open.
 */

interface VomBand { t: number; r0: number; r1: number; halfT: number }

const _p: RingPt = { x: 0, z: 0, nx: 0, nz: 0, t: 0, seg: 0 };

export interface BowlBuild {
  group: THREE.Group;
  seatCount: number;
}

export function buildBowl(ctx: Ctx, M: StadiumMaterials, rows: number, ringN: number): BowlBuild {
  const g = new THREE.Group();
  g.name = 'bowl';

  const topY = rowY(rows);
  const outerOff = rowOffset(rows);
  const concourseW = BOWL.concourseW;
  const hi = ctx.quality.tier === 'high' || ctx.quality.tier === 'ultra';

  /* ------------------------------------------------------------ vom bands */
  const voms: VomBand[] = VOMS.map((v) => ({
    t: AISLES[v.aisle % AISLES.length],
    r0: v.row0,
    r1: Math.min(rows - 3, v.row0 + v.span),
    halfT: v.halfW / perimeterAt(rowOffset(v.row0)),
  })).filter((v) => v.r1 > v.r0 + 2);

  const dT = (a: number, b: number) => { const d = Math.abs(a - b); return d > 0.5 ? 1 - d : d; };
  const vomAt = (t: number, r: number): VomBand | null => {
    for (const v of voms) if (r >= v.r0 && r < v.r1 && dT(t, v.t) < v.halfT) return v;
    return null;
  };
  const aisleAt = (t: number, off: number): boolean => {
    const half = AISLE_HALF / perimeterAt(off);
    for (const a of AISLES) if (dT(t, a) < half) return true;
    return false;
  };

  /* ----------------------------------------------------------- ring cache */
  // Sampled through ringTable so the corner arcs — which grow to a 40 m radius
  // by the back of the deck — are as finely tessellated as the straights.
  const tTab = ringTable(ringN);
  const N = tTab.length - 1;
  const ring: RingPt[] = [];
  for (let i = 0; i <= N; i++) {
    const p: RingPt = { x: 0, z: 0, nx: 0, nz: 0, t: 0, seg: 0 };
    ptAt(tTab[i] % 1, 0, p);
    p.t = tTab[i];
    ring.push(p);
  }
  const A: [number, number] = [0, 0], B: [number, number] = [0, 0];
  const C: [number, number] = [0, 0], D: [number, number] = [0, 0];
  const at = (i: number, off: number, out: [number, number]) => {
    const p = ring[Math.min(N, Math.max(0, i))];
    out[0] = p.x + p.nx * off; out[1] = p.z + p.nz * off;
  };
  const US = 0.29;  // world metres → texture repeats

  /* ============================================================ deck mesh */
  const deck = new Mesher();
  const uAt = (i: number) => ring[Math.min(N, i)].t * BASE_PERIMETER * US;

  // Pitch-side perimeter wall (LED boards hang on this) + front gangway.
  for (let i = 0; i < N; i++) {
    const u0 = uAt(i), u1 = uAt(i + 1), wy = BOWL.firstRowY;
    at(i, 0, A); at(i + 1, 0, B);
    deck.quad([A[0], 0, A[1]], [B[0], 0, B[1]], [B[0], wy, B[1]], [A[0], wy, A[1]],
      [u0, 0, u1, 0, u1, wy * US, u0, wy * US], [0.5, 0.5, 1, 1]);
    at(i + 1, rowOffset(0), C); at(i, rowOffset(0), D);
    deck.quad([A[0], wy, A[1]], [B[0], wy, B[1]], [C[0], wy, C[1]], [D[0], wy, D[1]],
      [u0, 0, u1, 0, u1, rowOffset(0) * US, u0, rowOffset(0) * US], [0.8, 0.8, 0.95, 0.95]);
  }

  // Treads + risers.
  let vAcc = rowOffset(0) * US;
  for (let r = 0; r < rows; r++) {
    const o0 = rowOffset(r), tread = rowTread(r), o1 = o0 + tread;
    const rise = rowRise(r);
    const y0 = rowY(r), y1 = y0 + rise;
    const vT0 = vAcc, vT1 = vAcc + tread * US, vR1 = vT1 + rise * US;
    vAcc = vR1;
    // The cross-aisle riser is a metre-plus wall; shade its base so the walkway
    // in front of it reads as a distinct band from a distance.
    const riserAo: number[] = isCrossAisleRow(r) ? [0.34, 0.34, 1.0, 1.0] : [0.5, 0.5, 1.0, 1.0];
    for (let i = 0; i < N; i++) {
      const tm = (ring[i].t + ring[i + 1].t) * 0.5;
      if (vomAt(tm, r)) continue;
      const u0 = uAt(i), u1 = uAt(i + 1);
      at(i, o0, A); at(i + 1, o0, B); at(i + 1, o1, C); at(i, o1, D);
      deck.quad([A[0], y0, A[1]], [B[0], y0, B[1]], [C[0], y0, C[1]], [D[0], y0, D[1]],
        [u0, vT0, u1, vT0, u1, vT1, u0, vT1], [0.98, 0.98, 0.62, 0.62]);
      deck.quad([D[0], y0, D[1]], [C[0], y0, C[1]], [C[0], y1, C[1]], [D[0], y1, D[1]],
        [u0, vT1, u1, vT1, u1, vR1, u0, vR1], riserAo);
    }
  }

  // Top concourse deck and parapet.
  const pO = outerOff + concourseW, pT = topY + BOWL.parapetH;
  for (let i = 0; i < N; i++) {
    const u0 = uAt(i), u1 = uAt(i + 1);
    at(i, outerOff, A); at(i + 1, outerOff, B);
    at(i + 1, outerOff + concourseW, C); at(i, outerOff + concourseW, D);
    deck.quad([A[0], topY, A[1]], [B[0], topY, B[1]], [C[0], topY, C[1]], [D[0], topY, D[1]],
      [u0, 0, u1, 0, u1, concourseW * US, u0, concourseW * US], [0.7, 0.7, 0.92, 0.92]);
    at(i, pO, A); at(i + 1, pO, B); at(i + 1, pO + 0.3, C); at(i, pO + 0.3, D);
    deck.quad([A[0], topY, A[1]], [B[0], topY, B[1]], [B[0], pT, B[1]], [A[0], pT, A[1]],
      [u0, 0, u1, 0, u1, BOWL.parapetH * US, u0, BOWL.parapetH * US], [0.68, 0.68, 1, 1]);
    deck.quad([A[0], pT, A[1]], [B[0], pT, B[1]], [C[0], pT, C[1]], [D[0], pT, D[1]],
      [u0, 0, u1, 0, u1, 0.3 * US, u0, 0.3 * US], [1, 1, 1, 1]);
  }

  const deckMesh = new THREE.Mesh(deck.build('bowl-deck'), M.concrete);
  deckMesh.castShadow = true; deckMesh.receiveShadow = true;
  g.add(deckMesh);

  /* ============================================================== facade */
  g.add(buildFacade(M, ring, N, uAt, at, A, B, C, D, pO, pT, US, hi));

  /* --------------------------------------------------------- vomitories */
  const vomM = new Mesher();
  for (const v of voms) {
    const yF = rowY(v.r0);
    const oIn = rowOffset(v.r0), oOut = rowOffset(v.r1);
    const iA = Math.max(0, Math.round(tIndex(tTab, v.t - v.halfT)));
    const iB = Math.min(N, Math.round(tIndex(tTab, v.t + v.halfT)));
    if (iB <= iA) continue;
    const head = Math.min(rowY(v.r1) - 0.25, yF + 2.7);
    const depth = 8.0;

    for (let i = iA; i < iB; i++) {
      const u0 = uAt(i), u1 = uAt(i + 1);
      // landing slab
      at(i, oIn, A); at(i + 1, oIn, B); at(i + 1, oOut, C); at(i, oOut, D);
      vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [C[0], yF, C[1]], [D[0], yF, D[1]],
        [u0, 0, u1, 0, u1, (oOut - oIn) * US, u0, (oOut - oIn) * US], [0.75, 0.75, 0.5, 0.5]);
      // tunnel ceiling / floor / back wall
      at(i, oOut, A); at(i + 1, oOut, B); at(i, oOut + depth, C); at(i + 1, oOut + depth, D);
      vomM.quad([A[0], head, A[1]], [B[0], head, B[1]], [D[0], head, D[1]], [C[0], head, C[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.12, 0.12, 0.03, 0.03]);
      vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [D[0], yF, D[1]], [C[0], yF, C[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.28, 0.28, 0.05, 0.05]);
      vomM.quad([C[0], yF, C[1]], [D[0], yF, D[1]], [D[0], head, D[1]], [C[0], head, C[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.05, 0.05, 0.03, 0.03]);
      // lintel across the top of the mouth
      vomM.quad([A[0], head, A[1]], [B[0], head, B[1]], [B[0], rowY(v.r1), B[1]], [A[0], rowY(v.r1), A[1]],
        [u0, 0, u1, 0, u1, 0.3, u0, 0.3], [0.55, 0.55, 0.85, 0.85]);
    }
    // stepped side walls of the cut + tunnel side walls
    for (const side of [iA, iB]) {
      for (let r = v.r0; r < v.r1; r++) {
        const o0 = rowOffset(r), o1 = o0 + rowTread(r);
        const y = rowY(r) + rowRise(r);
        at(side, o0, A); at(side, o1, B);
        const uu = r * BOWL.rowDepth * US, uu1 = uu + rowTread(r) * US, vv = (y - yF) * US;
        vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [B[0], y, B[1]], [A[0], y, A[1]],
          [uu, 0, uu1, 0, uu1, vv, uu, vv], [0.45, 0.45, 0.9, 0.9]);
      }
      at(side, oOut, A); at(side, oOut + depth, B);
      vomM.quad([A[0], yF, A[1]], [B[0], yF, B[1]], [B[0], head, B[1]], [A[0], head, A[1]],
        [0, 0, 1, 0, 1, 1, 0, 1], [0.1, 0.1, 0.06, 0.06]);
    }
  }
  const vomMesh = new THREE.Mesh(vomM.build('bowl-voms'), M.concreteDark);
  vomMesh.receiveShadow = true;
  g.add(vomMesh);

  /* ============================================================== aisles */
  // Each seating row splits into shallower steps inside the aisle, with a
  // painted nosing on every step. The cross-aisle row instead gets a flat
  // landing and a short flight up on to the upper tier. Lifted 2 cm off the
  // deck to avoid z-fighting.
  const stair = new Mesher();
  const railParts: Part[] = [];
  const NOSE: RGB = [2.1, 1.9, 0.95];
  const STEP: RGB = [1.16, 1.16, 1.13];
  const LIFT = 0.02;

  for (const aT of AISLES) {
    ptAt(aT, 0, _p);
    const nx = _p.nx, nz = _p.nz, tx = -nz, tz = nx;
    const bx = _p.x, bz = _p.z, hw = AISLE_HALF;

    for (let r = 0; r < rows; r++) {
      if (vomAt(aT, r)) continue;
      const o0 = rowOffset(r), rise = rowRise(r), y0 = rowY(r) + LIFT;
      const tread = rowTread(r);
      const brk = isCrossAisleRow(r);
      const flight = brk ? 1.45 : tread;
      const landing = tread - flight;
      const nSteps = brk ? 4 : 2;

      if (landing > 0.02) {
        const ax = bx + nx * o0, az = bz + nz * o0;
        const cx = bx + nx * (o0 + landing), cz = bz + nz * (o0 + landing);
        stair.quad(
          [ax - tx * hw, y0, az - tz * hw], [ax + tx * hw, y0, az + tz * hw],
          [cx + tx * hw, y0, cz + tz * hw], [cx - tx * hw, y0, cz - tz * hw],
          [0, 0, 1, 0, 1, 1, 0, 1], [1, 1, 0.8, 0.8], STEP);
      }

      const sd = flight / nSteps, sr = rise / nSteps;
      for (let s = 0; s < nSteps; s++) {
        const so = o0 + landing + s * sd;
        const sy = y0 + s * sr;
        const d = sd - 0.012;
        const ax = bx + nx * so, az = bz + nz * so;
        const cx = bx + nx * (so + d), cz = bz + nz * (so + d);
        stair.quad(
          [ax - tx * hw, sy, az - tz * hw], [ax + tx * hw, sy, az + tz * hw],
          [cx + tx * hw, sy, cz + tz * hw], [cx - tx * hw, sy, cz - tz * hw],
          [0, 0, 1, 0, 1, 1, 0, 1], [1, 1, 0.74, 0.74], STEP);
        const ex = bx + nx * (so + d - 0.06), ez = bz + nz * (so + d - 0.06);
        stair.quad(
          [ex - tx * hw, sy + 0.006, ez - tz * hw], [ex + tx * hw, sy + 0.006, ez + tz * hw],
          [cx + tx * hw, sy + 0.006, cz + tz * hw], [cx - tx * hw, sy + 0.006, cz - tz * hw],
          [0, 0, 1, 0, 1, 1, 0, 1], [1, 1, 1, 1], NOSE);
        stair.quad(
          [cx - tx * hw, sy, cz - tz * hw], [cx + tx * hw, sy, cz + tz * hw],
          [cx + tx * hw, sy + sr, cz + tz * hw], [cx - tx * hw, sy + sr, cz - tz * hw],
          [0, 0, 1, 0, 1, 1, 0, 1], [0.62, 0.62, 1, 1], STEP);
      }
    }

    // Handrails: one either side of the aisle, 1.0 m above the nosing line,
    // with a stanchion at every break in the run.
    const railStep = 3;
    for (const sgn of [-1, 1]) {
      const ox = bx + tx * sgn * (hw + 0.05), oz = bz + tz * sgn * (hw + 0.05);
      for (let r = 0; r < rows; r += railStep) {
        const r2 = Math.min(rows, r + railStep);
        const o1 = rowOffset(r) + rowSeatDepth(r) * 0.5, o2 = rowOffset(r2) + rowSeatDepth(r2) * 0.5;
        const p1: [number, number, number] = [ox + nx * o1, rowY(r) + 1.02, oz + nz * o1];
        const p2: [number, number, number] = [ox + nx * o2, rowY(r2) + 1.02, oz + nz * o2];
        railParts.push(strut(p1, p2, 0.055, UNIT_BOX));
        railParts.push(strut([p1[0], rowY(r), p1[2]], p1, 0.05, UNIT_BOX));
        // mid rail, half height
        const m1: [number, number, number] = [p1[0], p1[1] - 0.44, p1[2]];
        const m2: [number, number, number] = [p2[0], p2[1] - 0.44, p2[2]];
        if (hi) railParts.push(strut(m1, m2, 0.038, UNIT_BOX));
      }
    }
  }

  const stairMesh = new THREE.Mesh(stair.build('bowl-stairs'), M.concrete);
  stairMesh.receiveShadow = true;
  g.add(stairMesh);

  const railMesh = new THREE.Mesh(parts(railParts, 'bowl-rails'), M.steel);
  railMesh.castShadow = hi;
  railMesh.receiveShadow = true;
  g.add(railMesh);

  /* =============================================================== seats */
  // Exactly the slots published to peers through Layout.sampleSeats(), so the
  // crowd never sits on a seat that was not modelled and vice versa.
  const seatGeo = buildSeatGeometry(hi);
  const sampler = new SeatMapSampler();
  const slots = sampleSeats();

  const seats = new THREE.InstancedMesh(seatGeo, M.seat, slots.length);
  seats.name = 'seats';
  {
    const m4 = new THREE.Matrix4();
    const q = new THREE.Quaternion();
    const e = new THREE.Euler();
    const sc = new THREE.Vector3(1, 1, 1);
    const v3 = new THREE.Vector3();
    const col = new THREE.Color();
    const jitter = ctx.rand.fork(0x5ea7);
    const rowsM1 = Math.max(1, rows - 1);
    for (let i = 0; i < slots.length; i++) {
      const p = slots[i];
      e.set(0, p.yaw, 0);
      q.setFromEuler(e);
      v3.set(p.pos[0], p.pos[1], p.pos[2]);
      m4.compose(v3, q, sc);
      seats.setMatrixAt(i, m4);
      sampler.sample(p.t, p.row / rowsM1, col);
      col.multiplyScalar(0.9 + jitter.next() * 0.2);
      seats.setColorAt(i, col);
    }
  }
  seats.instanceMatrix.needsUpdate = true;
  if (seats.instanceColor) seats.instanceColor.needsUpdate = true;
  // ~16 k seats × every shadow cascade is the single biggest triangle bill in
  // the venue, and at 2048 the cascade texel is coarser than a seat back, so
  // the shadow is mush. The deck itself carries the shading; only ultra, with
  // a 4096 map, gets anything back for the cost.
  seats.castShadow = ctx.quality.tier === 'ultra';
  seats.receiveShadow = true;
  seats.frustumCulled = false;
  g.add(seats);

  /* ============================================================= signage */
  const signMat = M.signage.clone();
  signMat.map = bakeSignAtlas();
  signMat.name = 'signage';
  const sign = new Mesher();
  const cellU = 1 / 8, cellV = 1 / 12;
  const cellUV = (cell: number) => {
    const cx = cell % 8, cy = Math.floor(cell / 8);
    const u0 = cx * cellU, v1 = 1 - cy * cellV, v0 = v1 - cellV;
    return [u0, v0, u0 + cellU, v0, u0 + cellU, v1, u0, v1];
  };

  // Section plates on the parapet, read from outside and from a high camera.
  for (let a = 0; a < AISLES.length; a++) {
    ptAt(AISLES[a], 0, _p);
    const nx = _p.nx, nz = _p.nz, tx = -nz, tz = nx;
    const o = pO + 0.34;
    const x = _p.x + nx * o, z = _p.z + nz * o, y = topY + 0.66;
    const w = 0.82, h = 0.55;
    sign.quad([x - tx * w, y - h, z - tz * w], [x + tx * w, y - h, z + tz * w],
      [x + tx * w, y + h, z + tz * w], [x - tx * w, y + h, z - tz * w], cellUV(a % 32));
  }

  // …and matching plates on the cross-aisle riser, facing the pitch, centred
  // between aisles. That is where a real venue puts them.
  {
    const rB = Math.min(rows - 1, BOWL.lowerRows - 1);
    const yBase = rowY(rB) + rowRise(rB);
    const off = rowOffset(rB + 1) - 0.03;
    for (let a = 0; a < AISLE_COUNT; a++) {
      const t = (a + 1) / AISLE_COUNT;
      ptAt(t, 0, _p);
      const nx = _p.nx, nz = _p.nz, tx = -nz, tz = nx;
      const x = _p.x + nx * off, z = _p.z + nz * off;
      const y = yBase - 0.42;
      const w = 0.72, h = 0.34;
      sign.quad([x + tx * w, y - h, z + tz * w], [x - tx * w, y - h, z - tz * w],
        [x - tx * w, y + h, z - tz * w], [x + tx * w, y + h, z + tz * w], cellUV(a % 32));
    }
  }

  // Row numbers on every aisle nosing.
  for (const aT of AISLES) {
    ptAt(aT, 0, _p);
    const nx = _p.nx, nz = _p.nz, tx = -nz, tz = nx;
    for (let r = 0; r < rows; r++) {
      if (vomAt(aT, r)) continue;
      const o = rowOffset(r) + rowTread(r) - 0.018;
      const y = rowY(r) + LIFT + 0.03;
      const h = Math.min(0.2, rowRise(r) * 0.62);
      const x = _p.x + nx * o, z = _p.z + nz * o;
      const cx = x - tx * (AISLE_HALF - 0.19), cz = z - tz * (AISLE_HALF - 0.19);
      const hw = 0.15;
      sign.quad([cx - tx * hw, y, cz - tz * hw], [cx + tx * hw, y, cz + tz * hw],
        [cx + tx * hw, y + h, cz + tz * hw], [cx - tx * hw, y + h, cz - tz * hw],
        cellUV(32 + (r % 64)));
    }
  }
  g.add(new THREE.Mesh(sign.build('bowl-signage'), signMat));

  return { group: g, seatCount: slots.length };
}

/** Index into the ring table for a base parameter (the table is monotonic). */
function tIndex(tab: Float64Array, t: number): number {
  const tt = t - Math.floor(t);
  let lo = 0, hi = tab.length - 1;
  while (lo < hi) {
    const mid = (lo + hi) >> 1;
    if (tab[mid] < tt) lo = mid + 1; else hi = mid;
  }
  return lo;
}

/* ----------------------------------------------------------------- facade */

/**
 * The outer skin. A single flat wall from grade to the parapet is the fastest
 * way to make a stadium read as a lump of polystyrene, so this is banded: a
 * proud plinth, a recessed field carrying vertical concrete fins, a cornice
 * under the parapet, and eight recessed gate portals with canopies at grade.
 */
function buildFacade(
  M: StadiumMaterials,
  ring: RingPt[], N: number,
  uAt: (i: number) => number,
  at: (i: number, off: number, out: [number, number]) => void,
  A: [number, number], B: [number, number], C: [number, number], D: [number, number],
  pO: number, pT: number, US: number, hi: boolean,
): THREE.Group {
  const g = new THREE.Group();
  g.name = 'facade';

  const face = new Mesher();
  const PLINTH_Y = 1.75;
  const PLINTH_OUT = 0.42;
  const CORNICE_Y = pT - 1.05;
  const CORNICE_OUT = 0.30;
  const GATE_Y = 4.4;
  const GATE_IN = 1.05;
  const gateHalfT = 2.6 / perimeterAt(pO);

  const dT = (a: number, b: number) => { const d = Math.abs(a - b); return d > 0.5 ? 1 - d : d; };
  const gateAt = (t: number) => {
    for (const c of GATES) if (dT(t, c) < gateHalfT) return true;
    return false;
  };

  const o0 = pO + 0.3;
  for (let i = 0; i < N; i++) {
    const u0 = uAt(i), u1 = uAt(i + 1);
    const tm = (ring[i].t + ring[i + 1].t) * 0.5;
    const gate = gateAt(tm);
    const gateEdge = gate !== gateAt((ring[Math.max(0, i - 1)].t + ring[i].t) * 0.5);

    if (gate) {
      // Recessed portal: dark back face, soffit and a canopy lip.
      at(i, o0 - GATE_IN, A); at(i + 1, o0 - GATE_IN, B);
      face.quad([B[0], 0, B[1]], [A[0], 0, A[1]], [A[0], GATE_Y, A[1]], [B[0], GATE_Y, B[1]],
        [u1, 0, u0, 0, u0, GATE_Y * US, u1, GATE_Y * US], [0.10, 0.10, 0.24, 0.24]);
      at(i, o0, C); at(i + 1, o0, D);
      face.quad([B[0], GATE_Y, B[1]], [A[0], GATE_Y, A[1]], [C[0], GATE_Y, C[1]], [D[0], GATE_Y, D[1]],
        [u1, 0, u0, 0, u0, GATE_IN * US, u1, GATE_IN * US], [0.22, 0.22, 0.4, 0.4]);
      // wall above the portal
      face.quad([D[0], GATE_Y, D[1]], [C[0], GATE_Y, C[1]], [C[0], CORNICE_Y, C[1]], [D[0], CORNICE_Y, D[1]],
        [u1, 0, u0, 0, u0, (CORNICE_Y - GATE_Y) * US, u1, (CORNICE_Y - GATE_Y) * US], [0.72, 0.72, 1, 1]);
    } else {
      // Plinth, proud of the field.
      at(i, o0 + PLINTH_OUT, A); at(i + 1, o0 + PLINTH_OUT, B);
      face.quad([B[0], 0, B[1]], [A[0], 0, A[1]], [A[0], PLINTH_Y, A[1]], [B[0], PLINTH_Y, B[1]],
        [u1, 0, u0, 0, u0, PLINTH_Y * US, u1, PLINTH_Y * US], [0.66, 0.66, 1.12, 1.12]);
      at(i, o0, C); at(i + 1, o0, D);
      face.quad([B[0], PLINTH_Y, B[1]], [A[0], PLINTH_Y, A[1]], [C[0], PLINTH_Y, C[1]], [D[0], PLINTH_Y, D[1]],
        [u1, 0, u0, 0, u0, PLINTH_OUT * US, u1, PLINTH_OUT * US], [1.1, 1.1, 0.8, 0.8]);
      // Recessed field.
      face.quad([D[0], PLINTH_Y, D[1]], [C[0], PLINTH_Y, C[1]], [C[0], CORNICE_Y, C[1]], [D[0], CORNICE_Y, D[1]],
        [u1, 0, u0, 0, u0, (CORNICE_Y - PLINTH_Y) * US, u1, (CORNICE_Y - PLINTH_Y) * US], [0.86, 0.86, 1.14, 1.14]);
    }

    // Cornice band, proud again, running the whole way round.
    at(i, o0 + CORNICE_OUT, A); at(i + 1, o0 + CORNICE_OUT, B);
    at(i, o0, C); at(i + 1, o0, D);
    face.quad([D[0], CORNICE_Y, D[1]], [C[0], CORNICE_Y, C[1]], [A[0], CORNICE_Y, A[1]], [B[0], CORNICE_Y, B[1]],
      [u1, 0, u0, 0, u0, CORNICE_OUT * US, u1, CORNICE_OUT * US], [0.55, 0.55, 0.85, 0.85]);
    face.quad([B[0], CORNICE_Y, B[1]], [A[0], CORNICE_Y, A[1]], [A[0], pT, A[1]], [B[0], pT, B[1]],
      [u1, 0, u0, 0, u0, (pT - CORNICE_Y) * US, u1, (pT - CORNICE_Y) * US], [0.9, 0.9, 1, 1]);
    face.quad([B[0], pT, B[1]], [A[0], pT, A[1]], [C[0], pT, C[1]], [D[0], pT, D[1]],
      [u1, 0, u0, 0, u0, CORNICE_OUT * US, u1, CORNICE_OUT * US], [1, 1, 1, 1]);

    // Reveals at the sides of a portal — two windings so the jamb reads from
    // either approach without needing a double-sided material.
    if (gateEdge) {
      at(i, o0 - GATE_IN, A); at(i, o0, C);
      const uv = [0, 0, GATE_IN * US, 0, GATE_IN * US, GATE_Y * US, 0, GATE_Y * US];
      face.quad([A[0], 0, A[1]], [C[0], 0, C[1]], [C[0], GATE_Y, C[1]], [A[0], GATE_Y, A[1]],
        uv, [0.2, 0.3, 0.3, 0.2]);
      face.quad([C[0], 0, C[1]], [A[0], 0, A[1]], [A[0], GATE_Y, A[1]], [C[0], GATE_Y, C[1]],
        uv, [0.3, 0.2, 0.2, 0.3]);
    }
  }
  const faceMesh = new THREE.Mesh(face.build('bowl-facade'), M.concrete);
  faceMesh.castShadow = true; faceMesh.receiveShadow = true;
  g.add(faceMesh);

  /* -------------------------------------------------------------- fins */
  // Vertical concrete fins across the recessed field. They are what gives the
  // outside a rhythm and a shadow at low sun instead of a flat grey band.
  const fins: Part[] = [];
  const finGeo = UNIT_BOX;
  walkRow(o0, 4.4, (x, z, nx, nz, t) => {
    if (gateAt(t)) return;
    const yaw = Math.atan2(nx, nz);
    const h = CORNICE_Y - PLINTH_Y;
    fins.push({
      geo: finGeo,
      m: mat(x + nx * 0.24, PLINTH_Y + h / 2, z + nz * 0.24, 0, yaw, 0, 0.42, h, 0.52),
      color: [0.92, 0.92, 0.9] as RGB,
      uvScale: 0.5,
    });
    if (hi) {
      fins.push({
        geo: finGeo,
        m: mat(x + nx * 0.34, CORNICE_Y - 0.16, z + nz * 0.34, 0, yaw, 0, 0.5, 0.32, 0.7),
        color: [1.02, 1.02, 1.0] as RGB,
        uvScale: 0.5,
      });
    }
  });
  const finMesh = new THREE.Mesh(parts(fins, 'facade-fins'), M.concrete);
  finMesh.castShadow = true; finMesh.receiveShadow = true;
  g.add(finMesh);

  /* ------------------------------------------------------ gate canopies */
  const canopies: Part[] = [];
  for (const c of GATES) {
    ptAt(c, 0, _p);
    const nx = _p.nx, nz = _p.nz;
    const yaw = Math.atan2(nx, nz);
    const x = _p.x + nx * (o0 + 1.0), z = _p.z + nz * (o0 + 1.0);
    canopies.push({ geo: UNIT_BOX, m: mat(x, GATE_Y + 0.3, z, 0, yaw, 0, 7.2, 0.34, 3.0), color: [0.8, 0.82, 0.85] as RGB });
    for (const s of [-1, 1]) {
      const px = x - nz * s * 3.2, pz = z + nx * s * 3.2;
      canopies.push({ ...strut([px, 0, pz], [px, GATE_Y + 0.14, pz], 0.22, UNIT_BOX), color: [0.7, 0.72, 0.75] as RGB });
    }
  }
  const canopyMesh = new THREE.Mesh(parts(canopies, 'gate-canopies'), M.steel);
  canopyMesh.castShadow = true; canopyMesh.receiveShadow = true;
  g.add(canopyMesh);

  return g;
}

/* ------------------------------------------------------------------ seats */

/**
 * Folding stadium seat. The silhouette that matters at 40 m is: a raked back
 * with a slot across it, a real gap between the back and the pan, and a narrow
 * pedestal so the row reads as individual seats rather than a solid bench.
 */
function buildSeatGeometry(detailed: boolean): THREE.BufferGeometry {
  const BACK: RGB = [1, 1, 1];
  const PAN: RGB = [0.95, 0.95, 0.95];
  const FRAME: RGB = [0.4, 0.4, 0.42];
  const TILT = -0.15;

  const list: Part[] = detailed
    ? [
      // back, split by a moulded slot
      { geo: UNIT_BOX, m: mat(0, 0.585, -0.135, TILT, 0, 0, 0.455, 0.20, 0.055), color: BACK, uvScale: 0.9 },
      { geo: UNIT_BOX, m: mat(0, 0.815, -0.170, TILT, 0, 0, 0.455, 0.21, 0.055), color: BACK, uvScale: 0.9 },
      // pan, nosed down at the front
      { geo: UNIT_BOX, m: mat(0, 0.440, 0.055, 0.05, 0, 0, 0.455, 0.065, 0.40), color: PAN, uvScale: 0.9 },
      // arms
      { geo: UNIT_BOX, m: mat(0.245, 0.545, -0.02, 0, 0, 0, 0.045, 0.10, 0.34), color: [0.74, 0.74, 0.75] },
      { geo: UNIT_BOX, m: mat(-0.245, 0.545, -0.02, 0, 0, 0, 0.045, 0.10, 0.34), color: [0.74, 0.74, 0.75] },
      // pedestal, on a foot plate
      { geo: UNIT_BOX, m: mat(0, 0.215, -0.055, 0, 0, 0, 0.13, 0.43, 0.10), color: FRAME },
    ]
    : [
      { geo: UNIT_BOX, m: mat(0, 0.700, -0.150, TILT, 0, 0, 0.455, 0.44, 0.055), color: BACK, uvScale: 0.9 },
      { geo: UNIT_BOX, m: mat(0, 0.442, 0.055, 0.05, 0, 0, 0.455, 0.060, 0.40), color: PAN, uvScale: 0.9 },
      { geo: UNIT_BOX, m: mat(0, 0.215, -0.055, 0, 0, 0, 0.14, 0.43, 0.10), color: FRAME },
    ];
  return parts(list, 'seat');
}

/* ---------------------------------------------------------------- signage */

/** 8×12 atlas: cells 0..31 section plates "101"…"132", 32..95 row numbers. */
function bakeSignAtlas(): THREE.CanvasTexture {
  return canvasTexture(1024, 1024, (c, W, H) => {
    c.clearRect(0, 0, W, H);
    const cw = W / 8, ch = H / 12;
    c.textAlign = 'center';
    c.textBaseline = 'middle';
    for (let cell = 0; cell < 96; cell++) {
      const cx = (cell % 8) * cw, cy = Math.floor(cell / 8) * ch;
      if (cell < 32) {
        c.fillStyle = '#0d1c2c';
        c.fillRect(cx + 6, cy + 10, cw - 12, ch - 20);
        c.strokeStyle = '#d9a441';
        c.lineWidth = 3;
        c.strokeRect(cx + 6, cy + 10, cw - 12, ch - 20);
        c.fillStyle = '#f2f5f7';
        c.font = '700 42px "Helvetica Neue", Helvetica, Arial, sans-serif';
        c.fillText(String(101 + cell), cx + cw / 2, cy + ch / 2 + 6);
        c.font = '600 14px "Helvetica Neue", Helvetica, Arial, sans-serif';
        c.fillStyle = '#9fb4c6';
        c.fillText('SECTION', cx + cw / 2, cy + 24);
      } else {
        c.fillStyle = '#efe9d8';
        c.font = '800 44px "Helvetica Neue", Helvetica, Arial, sans-serif';
        c.fillText(String(cell - 31), cx + cw / 2, cy + ch / 2);
      }
    }
  }, { name: 'sign-atlas', anisotropy: 8 });
}
